routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\FrontEndController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/accueil', 301);
Route::get('accueil', function(){
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{role}', [FrontEndController::class, 'admin'])->name('admin');
Route::get('login/{role}', [FrontEndController::class, 'entity'])->name('entity');
Route::post('login-entity', [LoginController::class, 'loginEntity']);


Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('posts', App\Http\Controllers\PostController::class);
    
    Route::resource('media', App\Http\Controllers\MediaController::class);
    
    Route::resource('criticals', App\Http\Controllers\CriticalController::class);
    
    Route::resource('propositions', App\Http\Controllers\PropositionController::class);
    
    Route::resource('commentTypes', App\Http\Controllers\CommentTypeController::class);
    
    Route::resource('likes', App\Http\Controllers\LikeController::class);
    
    Route::resource('entityTypes', App\Http\Controllers\EntityTypeController::class);
    
    Route::resource('entities', App\Http\Controllers\EntityController::class);

    Route::resource('agents', App\Http\Controllers\AgentController::class);
    
    Route::resource('products', App\Http\Controllers\ProductController::class);
    
    Route::resource('categories', App\Http\Controllers\CategoryController::class);
    
});

app/Http/Controllers/EntityTypeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEntityTypeRequest;
use App\Http\Requests\UpdateEntityTypeRequest;
use App\Repositories\EntityTypeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class EntityTypeController extends AppBaseController
{
    /** @var  EntityTypeRepository */
    private $entityTypeRepository;

    public function __construct(EntityTypeRepository $entityTypeRepo)
    {
        $this->entityTypeRepository = $entityTypeRepo;
    }

    /**
     * Display a listing of the EntityType.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $entityTypes = $this->entityTypeRepository->all();

        return view('entity_types.index')
            ->with('entityTypes', $entityTypes);
    }

    /**
     * Show the form for creating a new EntityType.
     *
     * @return Response
     */
    public function create()
    {
        return view('entity_types.create');
    }

    /**
     * Store a newly created EntityType in storage.
     *
     * @param CreateEntityTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateEntityTypeRequest $request)
    {
        $input = $request->all();

        $entityType = $this->entityTypeRepository->create($input);

        Flash::success('Entity Type saved successfully.');

        return redirect(route('entityTypes.index'));
    }

    /**
     * Display the specified EntityType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $entityType = $this->entityTypeRepository->find($id);

        if (empty($entityType)) {
            Flash::error('Entity Type not found');

            return redirect(route('entityTypes.index'));
        }

        return view('entity_types.show')->with('entityType', $entityType);
    }

    /**
     * Show the form for editing the specified EntityType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $entityType = $this->entityTypeRepository->find($id);

        if (empty($entityType)) {
            Flash::error('Entity Type not found');

            return redirect(route('entityTypes.index'));
        }

        return view('entity_types.edit')->with('entityType', $entityType);
    }

    /**
     * Update the specified EntityType in storage.
     *
     * @param int $id
     * @param UpdateEntityTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEntityTypeRequest $request)
    {
        $entityType = $this->entityTypeRepository->find($id);

        if (empty($entityType)) {
            Flash::error('Entity Type not found');

            return redirect(route('entityTypes.index'));
        }

        $entityType = $this->entityTypeRepository->update($request->all(), $id);

        Flash::success('Entity Type updated successfully.');

        return redirect(route('entityTypes.index'));
    }

    /**
     * Remove the specified EntityType from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $entityType = $this->entityTypeRepository->find($id);

        if (empty($entityType)) {
            Flash::error('Entity Type not found');

            return redirect(route('entityTypes.index'));
        }

        $this->entityTypeRepository->delete($id);

        Flash::success('Entity Type deleted successfully.');

        return redirect(route('entityTypes.index'));
    }
}

resources/views/entity_types/create.blade.php
@extends('layouts.app')
@section('title')
     Type Entite 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">Type Entite </h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('entityTypes.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'entityTypes.store']) !!}
                                    <div class="row">
                                        @include('entity_types.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/entity_types/edit.blade.php
@extends('layouts.app')
@section('title')
    Modification Type Entite
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Type Entite</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('entityTypes.index') }}"  class="btn btn-primary">Retour</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($entityType, ['route' => ['entityTypes.update', $entityType->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('entity_types.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/entity_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nom:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Enregistrer', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('entityTypes.index') }}" class="btn btn-light">Annuler</a>
</div>

resources/views/entity_types/index.blade.php
@extends('layouts.app')
@section('title')
    Type d'entités
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Type d'entités</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('entityTypes.create')}}" class="btn btn-primary form-btn">Type d'entités <i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('entity_types.table')
            </div>
       </div>
   </div>

    </section>
@endsection

resources/views/entity_types/show.blade.php
@extends('layouts.app')
@section('title')
    Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1> Type entite Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('entityTypes.index') }}"
                 class="btn btn-primary form-btn float-right">Retour</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('entity_types.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/entity_types/show_fields.blade.php
<div class="row">

    <!-- Name Field -->
    <div class="col-md-6">
        {!! Form::label('name', 'Nom:') !!}
        <p>{{ $entityType->name }}</p>
    </div>

    <!-- Description Field -->
    <div class="col-md-6">
        {!! Form::label('description', 'Description:') !!}
        <p>{{ $entityType->description }}</p>
    </div>

    <!-- Created At Field -->
    <div class="col-md-6">
        {!! Form::label('created_at', 'Date de creation:') !!}
        <p>{{ $entityType->created_at }}</p>
    </div>

    <!-- Updated At Field -->
    <div class="col-md-6">
        {!! Form::label('updated_at', 'Date de la derniere modification:') !!}
        <p>{{ $entityType->updated_at }}</p>
    </div>
</div>

resources/views/entity_types/table.blade.php
<div class="table-responsive">
    <table class="table" id="entityTypes-table">
        <thead>
            <tr>
                <th>Nom </th>
                <th>Description</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($entityTypes as $entityType)
            <tr>
                       <td>{{ $entityType->name }}</td>
            <td>{!! $entityType->description !!}</td>
                       <td class=" text-center">
                           {!! Form::open(['route' => ['entityTypes.destroy', $entityType->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('entityTypes.show', [$entityType->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('entityTypes.edit', [$entityType->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
        @endforeach
        </tbody>
    </table>
</div>