routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\FrontEndController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/accueil', 301);
Route::get('accueil', function(){
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('login/{role}', [FrontEndController::class, 'admin'])->name('admin');
Route::get('login/{role}', [FrontEndController::class, 'entity'])->name('entity');
Route::post('login-entity', [LoginController::class, 'loginEntity']);


Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('posts', App\Http\Controllers\PostController::class);
    
    Route::resource('media', App\Http\Controllers\MediaController::class);
    
    Route::resource('criticals', App\Http\Controllers\CriticalController::class);
    
    Route::resource('propositions', App\Http\Controllers\PropositionController::class);
    
    Route::resource('commentTypes', App\Http\Controllers\CommentTypeController::class);
    
    Route::resource('likes', App\Http\Controllers\LikeController::class);
    
    Route::resource('entityTypes', App\Http\Controllers\EntityTypeController::class);
    
    Route::resource('entities', App\Http\Controllers\EntityController::class);

    Route::resource('agents', App\Http\Controllers\AgentController::class);
    
    Route::resource('products', App\Http\Controllers\ProductController::class);
    
    Route::resource('categories', App\Http\Controllers\CategoryController::class);
    
});

app/Http/Controllers/CommentTypeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCommentTypeRequest;
use App\Http\Requests\UpdateCommentTypeRequest;
use App\Repositories\CommentTypeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Flash;
use Response;

class CommentTypeController extends AppBaseController
{
    /** @var  CommentTypeRepository */
    private $commentTypeRepository;

    public function __construct(CommentTypeRepository $commentTypeRepo)
    {
        $this->commentTypeRepository = $commentTypeRepo;
    }

    /**
     * Display a listing of the CommentType.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $commentTypes = $this->commentTypeRepository->all();

        return view('comment_types.index')
            ->with('commentTypes', $commentTypes);
    }

    /**
     * Show the form for creating a new CommentType.
     *
     * @return Response
     */
    public function create()
    {
        return view('comment_types.create');
    }

    /**
     * Store a newly created CommentType in storage.
     *
     * @param CreateCommentTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateCommentTypeRequest $request)
    {
        $input = $request->all();

        $input['slug'] = Str::slug($input['name']);

        $commentType = $this->commentTypeRepository->create($input);

        Flash::success('Comment Type saved successfully.');

        return redirect(route('commentTypes.index'));
    }

    /**
     * Display the specified CommentType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $commentType = $this->commentTypeRepository->find($id);

        if (empty($commentType)) {
            Flash::error('Comment Type not found');

            return redirect(route('commentTypes.index'));
        }

        return view('comment_types.show')->with('commentType', $commentType);
    }

    /**
     * Show the form for editing the specified CommentType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $commentType = $this->commentTypeRepository->find($id);

        if (empty($commentType)) {
            Flash::error('Comment Type not found');

            return redirect(route('commentTypes.index'));
        }

        return view('comment_types.edit')->with('commentType', $commentType);
    }

    /**
     * Update the specified CommentType in storage.
     *
     * @param int $id
     * @param UpdateCommentTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCommentTypeRequest $request)
    {
        $commentType = $this->commentTypeRepository->find($id);

        if (empty($commentType)) {
            Flash::error('Comment Type not found');

            return redirect(route('commentTypes.index'));
        }

        $commentType = $this->commentTypeRepository->update($request->all(), $id);

        Flash::success('Comment Type updated successfully.');

        return redirect(route('commentTypes.index'));
    }

    /**
     * Remove the specified CommentType from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $commentType = $this->commentTypeRepository->find($id);

        if (empty($commentType)) {
            Flash::error('Comment Type not found');

            return redirect(route('commentTypes.index'));
        }

        $this->commentTypeRepository->delete($id);

        Flash::success('Comment Type deleted successfully.');

        return redirect(route('commentTypes.index'));
    }
}

resources/views/comment_types/create.blade.php
@extends('layouts.app')
@section('title')
    Create Comment Type 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Comment Type</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('commentTypes.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'commentTypes.store']) !!}
                                    <div class="row">
                                        @include('comment_types.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/comment_types/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Comment Type 
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Edit Comment Type</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('commentTypes.index') }}"  class="btn btn-primary">Back</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($commentType, ['route' => ['commentTypes.update', $commentType->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('comment_types.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/comment_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('slug', 'Slug:') !!}
    {!! Form::text('slug', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('commentTypes.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/comment_types/index.blade.php
@extends('layouts.app')
@section('title')
    Comment Types
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Type de Commentaires</h1>
            {{-- <div class="section-header-breadcrumb">
                <a href="{{ route('commentTypes.create')}}" class="btn btn-primary form-btn">Comment Type <i class="fas fa-plus"></i></a>
            </div> --}}
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('comment_types.table')
            </div>
       </div>
   </div>

    </section>
@endsection

resources/views/comment_types/show.blade.php
@extends('layouts.app')
@section('title')
    Comment Type Details 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>Comment Type Details</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('commentTypes.index') }}"
                 class="btn btn-primary form-btn float-right">Back</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('comment_types.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/comment_types/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $commentType->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $commentType->description }}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Slug:') !!}
    <p>{{ $commentType->slug }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $commentType->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $commentType->updated_at }}</p>
</div>

resources/views/comment_types/table.blade.php
<div class="table-responsive">
    <table class="table" id="commentTypes-table">
        <thead>
            <tr>
                <th>Nom </th>
                <th>Description</th>
                {{-- <th>Slug</th> --}}
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($commentTypes as $commentType)
            <tr>
                       <td>{{ $commentType->name }}</td>
            <td>{{ $commentType->description }}</td>
            {{-- <td>{{ $commentType->slug }}</td> --}}
                       <td class=" text-center">
                           {!! Form::open(['route' => ['commentTypes.destroy', $commentType->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('commentTypes.show', [$commentType->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('commentTypes.edit', [$commentType->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
        @endforeach
        </tbody>
    </table>
</div>